{
  "draw_open": {
    "en": "OPEN",
    "zh-rHK": "WEP",
    "zh-rCN": "打开",
    "th": "เปิด",
    "es": "Abrir",
    "es-rLA": "Abrir",
    "fr": "Ouvrir",
    "fr-rCA": "Ouvrir",
    "de": "Öffnen",
    "ru": "Открыть",
    "sk": "Otvoriť",
    "it": "Apri",
    "ar": "فتح",
    "pt": "Abrir",
    "tr": "Aç",
    "vi": "Mở",
    "in": "Buka",
    "ms": "Buka",
    "da": "Åbn",
    "cs": "Otevřít",
    "pl": "Otwórz",
    "hu": "Megnyitás",
    "fi": "Avaa",
    "nl": "Openen",
    "sv": "Öppna",
    "hr": "Otvori",
    "ro": "Deschideți",
    "sl": "Odpri",
    "el": "Άνοιγμα",
    "bg": "Отваряне",
    "uk": "Відкрити",
    "pt-rBR": "Abrir",
    "ca": "Obrir",
    "fa": "باز كردن",
    "sr": "Otvori",
    "ko": "OPEN",
    "ja": "開く",
    "no": "Åpne",
    "mk": "Отвори",
    "gl": "Abrir",
    "eu": "Ireki",
    "sq": "Hapni",
    "lv": "Atvērt",
    "lt": "Atidaryti",
    "et": "Puudub",
    "ur": "OPEN"
  },
  "user_download": {
    "en": "DOWNLOAD",
    "zh-rHK": "下載",
    "zh-rCN": "下载",
    "th": "ดาวน์โหลด",
    "es": "DESCARGAR",
    "es-rLA": "DESCARGAR",
    "fr": "TÉLÉCHARGER",
    "fr-rCA": "TÉLÉCHARGER",
    "de": "HERUNTERLADEN",
    "ru": "ЗАГРУЗИТЬ",
    "sk": "PREVZIAŤ",
    "it": "SCARICA",
    "ar": "تنزيل",
    "pt": "TRANSFERIR",
    "tr": "İNDİR",
    "vi": "TẢI XUỐNG",
    "in": "UNDUH",
    "ms": "MUAT TURUN",
    "da": "DOWNLOAD",
    "cs": "STÁHNOUT",
    "pl": "POBIERZ",
    "hu": "LETÖLTÉS",
    "fi": "LATAA",
    "nl": "DOWNLOADEN",
    "sv": "HÄMTA",
    "hr": "PREUZIMANJE",
    "ro": "DESCĂRCAȚI",
    "sl": "PRENOS",
    "el": "ΛΗΨΗ",
    "bg": "ИЗТЕГЛЯНЕ",
    "uk": "ЗАВАНТАЖИТИ",
    "pt-rBR": "BAIXAR",
    "ca": "BAIXAR",
    "fa": "دانلود",
    "sr": "PREUZMI",
    "ko": "다운로드",
    "ja": "DOWNLOAD",
    "no": "NEDLASTING",
    "mk": "ПРЕВЗЕМИ",
    "gl": "DESCARGAR",
    "eu": "DESKARGATU",
    "sq": "SHKARKONI",
    "lv": "LEJUPIELĀDĒT",
    "lt": "ATSISIŲSTI",
    "et": "LAADI ALLA",
    "ur": "DOWNLOAD"
  },
  "user_manual_download": {
    "en": "Download user manual",
    "zh-rHK": "下載使用者手冊",
    "zh-rCN": "下载用户手册",
    "th": "ดาวน์โหลดคู่มือผู้ใช้",
    "es": "Descargar el manual de usuario",
    "es-rLA": "Descargar el manual de usuario",
    "fr": "Télécharger le mode d’emploi",
    "fr-rCA": "Télécharger le guide de l’utilisateur",
    "de": "Benutzerhandbuch herunterladen",
    "ru": "Загрузить руководство пользователя",
    "sk": "Stiahnuť používateľskú príručku",
    "it": "Scarica manuale utente",
    "ar": "تنزيل دليل المستخدم",
    "pt": "Transferir o manual de utilizador",
    "tr": "Kullanıcı kılavuzunu indir",
    "vi": "Tải xuống hướng dẫn sử dụng",
    "in": "Unduh panduan pengguna",
    "ms": "Muat turun manual pengguna",
    "da": "Download brugervejledning",
    "cs": "Stáhnout uživatelskou příručku",
    "pl": "Pobierz podręcznik użytkownika",
    "hu": "Használati útmutató letöltése",
    "fi": "Lataa käyttäjän käsikirja",
    "nl": "Gebruikershandleiding downloaden",
    "sv": "Ladda ned användarhandbok",
    "hr": "Preuzimanje korisničkih uputa",
    "ro": "Descărcați manualul de utilizare",
    "sl": "Prenos uporabniškega priročnika",
    "el": "Λήψη εγχειριδίου χρήστη",
    "bg": "Изтегляне на ръководство за потребителя",
    "uk": "Завантажити посібник користувача",
    "pt-rBR": "Baixar o manual do usuário",
    "ca": "Baixeu el manual d'usuari",
    "fa": "دانلود دفترچه راهنمای کاربر",
    "sr": "Preuzmite priručnik za upotrebu",
    "ko": "사용 설명서 다운로드",
    "ja": "ユーザーマニュアルのダウンロード",
    "no": "Last ned brukermanual",
    "mk": "Преземете го упатството за употреба",
    "gl": "Descargar manual de usuario",
    "eu": "Deskargatu erabiltzailearen eskuliburua",
    "sq": "Shkarko manualin e përdorimit",
    "lv": "Lejupielādēt pamācību",
    "lt": "Atsisiųsti naudotojo vadovą",
    "et": "Laadi alla kasutusjuhend",
    "ur": "صارف رہنما کتابچہ ڈاؤن لوڈ کریں"
  },
  "user_manual": {
    "en": "User manual",
    "zh-rHK": "使用者手冊",
    "zh-rCN": "用户手册",
    "th": "คู่มือผู้ใช้",
    "es": "Manual del usuario",
    "es-rLA": "Instructivo de uso",
    "fr": "Mode d’emploi",
    "fr-rCA": "Guide de l’utilisateur",
    "de": "Benutzerhandbuch",
    "ru": "Руководство пользователя",
    "sk": "Používateľská príručka",
    "it": "\"Manuale dell\\'utente\"",
    "ar": "دليل المستخدم",
    "pt": "Manual do utilizador",
    "tr": "Kullanıcı kılavuzu",
    "vi": "Hướng dẫn sử dụng",
    "in": "Panduan bagi pengguna",
    "ms": "Manual pengguna",
    "da": "Brugervejledning",
    "cs": "Uživatelská příručka",
    "pl": "Podręcznik użytkownika",
    "hu": "Használati útmutató",
    "fi": "Käyttöopas",
    "nl": "Gebruikershandleiding",
    "sv": "Användarhandbok",
    "hr": "Korisnički priručnik",
    "ro": "Manual de utilizare",
    "sl": "Uporabniški priročnik",
    "el": "Εγχειρίδιο χρήστη",
    "bg": "Ръководство за потребителя",
    "uk": "Посібник користувача",
    "pt-rBR": "Manual do usuário",
    "ca": "\"Manual d\\'usuari\"",
    "fa": "راهنمای کاربر",
    "sr": "Uputstvo za upotrebu",
    "ko": "사용 설명서",
    "ja": "User manual",
    "no": "Brukermanual",
    "mk": "Упатство за употреба",
    "gl": "Manual de usuario",
    "eu": "Erabiltzailearen gida",
    "sq": "Manuali i përdoruesit",
    "lv": "Lietošanas rokasgrāmata",
    "lt": "Naudotojo vadovas",
    "et": "Kasutusjuhend",
    "ur": "User manual"
  },
  "other_version": {
    "en": "Other version",
    "zh-rHK": "其他版本",
    "zh-rCN": "其他版本",
    "th": "เวอร์ชันอื่นๆ",
    "es": "Otra versión",
    "es-rLA": "Otra versión",
    "fr": "Autre version",
    "fr-rCA": "Autre version",
    "de": "Andere Version",
    "ru": "Other version",
    "sk": "Iná verzia",
    "it": "Altra versione",
    "ar": "إصدار آخر",
    "pt": "Outra versão",
    "tr": "Diğer sürüm",
    "vi": "Phiên bản khác",
    "in": "Versi lain",
    "ms": "Versi lain",
    "da": "Anden version",
    "cs": "Jiná verze",
    "pl": "Inna wersja",
    "hu": "Egyéb verzió",
    "fi": "Toinen versio",
    "nl": "Andere versie",
    "sv": "Annan version",
    "hr": "Una altra versió",
    "ro": "Altă versiune",
    "sl": "Druga različica",
    "el": "Άλλη έκδοση",
    "bg": "Друга версия",
    "uk": "Інша версія",
    "pt-rBR": "Outra versão",
    "ca": "Una altra versió",
    "fa": "نسخه دیگر",
    "sr": "Druga verzija",
    "ko": "다른 버전",
    "ja": "その他のバージョン",
    "no": "Annen versjon",
    "mk": "Друга верзија",
    "gl": "Outra versión",
    "eu": "Beste bertsio bat",
    "sq": "Versioni tjetër",
    "lv": "Cita versija",
    "lt": "Kita versija",
    "et": "Kita versija",
    "ur": "دیگر ورژن"
  }
}